// Package intent recomputes, inside the gateway, the SPT-Txn intent digest an
// MCP enforcement point binds a tool-call to (DELEGATION-INTENT-MCP §2), and
// derives rail values from it under their own domain tags (SPEC-ARC-M3 §4.1.4,
// §6).
//
// The canonicalizer here is a minimal RFC 8785 (JCS) restricted to exactly the
// subset the reference implementation accepts, and nothing wider:
//
//   - objects with unique member names; arrays; strings; true, false, null;
//   - integers with no sign other than a leading '-', no leading zero, no
//     fraction, no exponent, not "-0", and |n| <= 2^53-1;
//   - strings that are valid UTF-8 and do not contain U+FFFD (the decoder maps
//     invalid escapes, lone surrogates and invalid bytes to U+FFFD, so two
//     different inputs could otherwise canonicalize alike);
//   - nesting depth at most 64.
//
// Anything else is refused, never normalized. It is proven byte-for-byte
// against the reference by checked-in vectors (testdata/jcs-vectors.json),
// generated by running the reference, so this package carries no dependency on
// it. Standard library only.
package intent

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

const (
	maxDepth = 64
	maxInt   = int64(1)<<53 - 1
)

// Refusal classes. Every refusal wraps exactly one of these.
var (
	ErrSyntax    = errors.New("intent/jcs: malformed JSON")
	ErrDuplicate = errors.New("intent/jcs: duplicate object member")
	ErrNumber    = errors.New("intent/jcs: number outside the accepted subset (integers |n| <= 2^53-1 only)")
	ErrString    = errors.New("intent/jcs: string not valid UTF-8 or contains U+FFFD")
	ErrDepth     = errors.New("intent/jcs: nesting deeper than 64")
)

// Canonicalize parses raw JSON under the subset rules and returns its
// canonical bytes. It is the only entry point: callers hand it what they
// received, never a value they have already decoded.
func Canonicalize(raw []byte) ([]byte, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	v, err := readValue(dec, 0)
	if err != nil {
		return nil, err
	}
	if _, err := dec.Token(); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("%w: data after the value", ErrSyntax)
	}
	var buf bytes.Buffer
	write(&buf, v)
	return buf.Bytes(), nil
}

// member is an object member; objects keep members as a slice so ordering is
// done once, explicitly, at write time.
type member struct {
	key string
	val any
}

type object []member

func readValue(dec *json.Decoder, depth int) (any, error) {
	if depth > maxDepth {
		return nil, ErrDepth
	}
	tok, err := dec.Token()
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrSyntax, err)
	}
	switch t := tok.(type) {
	case json.Delim:
		switch t {
		case '{':
			var obj object
			seen := map[string]bool{}
			for dec.More() {
				kt, err := dec.Token()
				if err != nil {
					return nil, fmt.Errorf("%w: %v", ErrSyntax, err)
				}
				k, ok := kt.(string)
				if !ok {
					return nil, fmt.Errorf("%w: member name is not a string", ErrSyntax)
				}
				if err := checkString(k); err != nil {
					return nil, err
				}
				if seen[k] {
					return nil, fmt.Errorf("%w: %q", ErrDuplicate, k)
				}
				seen[k] = true
				v, err := readValue(dec, depth+1)
				if err != nil {
					return nil, err
				}
				obj = append(obj, member{k, v})
			}
			if _, err := dec.Token(); err != nil {
				return nil, fmt.Errorf("%w: %v", ErrSyntax, err)
			}
			if obj == nil {
				obj = object{}
			}
			return obj, nil
		case '[':
			arr := []any{}
			for dec.More() {
				v, err := readValue(dec, depth+1)
				if err != nil {
					return nil, err
				}
				arr = append(arr, v)
			}
			if _, err := dec.Token(); err != nil {
				return nil, fmt.Errorf("%w: %v", ErrSyntax, err)
			}
			return arr, nil
		}
		return nil, fmt.Errorf("%w: unexpected %v", ErrSyntax, t)
	case string:
		if err := checkString(t); err != nil {
			return nil, err
		}
		return t, nil
	case json.Number:
		n, err := integer(string(t))
		if err != nil {
			return nil, err
		}
		return n, nil
	case bool, nil:
		return t, nil
	}
	return nil, fmt.Errorf("%w: unexpected token %T", ErrSyntax, tok)
}

// integer accepts only -?(0|[1-9][0-9]*) within ±(2^53-1), and not "-0".
func integer(s string) (int64, error) {
	body := strings.TrimPrefix(s, "-")
	if body == "" || s == "-0" || (body[0] == '0' && len(body) > 1) {
		return 0, ErrNumber
	}
	for i := 0; i < len(body); i++ {
		if body[i] < '0' || body[i] > '9' {
			return 0, ErrNumber
		}
	}
	n, err := strconv.ParseInt(s, 10, 64)
	if err != nil || n > maxInt || n < -maxInt {
		return 0, ErrNumber
	}
	return n, nil
}

func checkString(s string) error {
	if !utf8.ValidString(s) || strings.ContainsRune(s, utf8.RuneError) {
		return ErrString
	}
	return nil
}

func write(buf *bytes.Buffer, v any) {
	switch t := v.(type) {
	case nil:
		buf.WriteString("null")
	case bool:
		buf.WriteString(strconv.FormatBool(t))
	case int64:
		buf.WriteString(strconv.FormatInt(t, 10))
	case string:
		writeString(buf, t)
	case []any:
		buf.WriteByte('[')
		for i, e := range t {
			if i > 0 {
				buf.WriteByte(',')
			}
			write(buf, e)
		}
		buf.WriteByte(']')
	case object:
		sorted := append(object(nil), t...)
		sort.Slice(sorted, func(i, j int) bool { return utf16Before(sorted[i].key, sorted[j].key) })
		buf.WriteByte('{')
		for i, m := range sorted {
			if i > 0 {
				buf.WriteByte(',')
			}
			writeString(buf, m.key)
			buf.WriteByte(':')
			write(buf, m.val)
		}
		buf.WriteByte('}')
	default:
		// Unreachable: readValue produces only the types above.
		panic(fmt.Sprintf("intent/jcs: internal type %T", v))
	}
}

// writeString is RFC 8785 §3.2.2.2: \" \\ \b \f \n \r \t, other C0 controls as
// lowercase \u00xx, everything else (including '/', DEL, U+2028, U+2029 and
// non-BMP characters) as literal UTF-8.
func writeString(buf *bytes.Buffer, s string) {
	const hex = "0123456789abcdef"
	buf.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			buf.WriteString(`\"`)
		case '\\':
			buf.WriteString(`\\`)
		case '\b':
			buf.WriteString(`\b`)
		case '\f':
			buf.WriteString(`\f`)
		case '\n':
			buf.WriteString(`\n`)
		case '\r':
			buf.WriteString(`\r`)
		case '\t':
			buf.WriteString(`\t`)
		default:
			if r < 0x20 {
				buf.WriteString(`\u00`)
				buf.WriteByte(hex[r>>4])
				buf.WriteByte(hex[r&0xf])
			} else {
				buf.WriteRune(r)
			}
		}
	}
	buf.WriteByte('"')
}

// utf16Before orders member names by UTF-16 code units (RFC 8785 §3.2.3), which
// differs from UTF-8 byte order for U+E000..U+FFFF against non-BMP characters.
func utf16Before(a, b string) bool {
	ua, ub := utf16.Encode([]rune(a)), utf16.Encode([]rune(b))
	for i := 0; i < len(ua) && i < len(ub); i++ {
		if ua[i] != ub[i] {
			return ua[i] < ub[i]
		}
	}
	return len(ua) < len(ub)
}
